### ISSUE TITLE
Move Example to Top of the Playground

### ISSUE THREAD

**Issue by jefrydco** [isdzulqor/cakcuk#3]
I spend nearly 10s to figure out what should I do when the playground page is opened. It turns out the example is located in the bottom of the playground. I can help refactor it if you wish, but first perhaps would you like add some explanation how to run it in development mode :smiley:

**Comment by isdzulqor** [comment]
Hi @jefrydco, thanks for your issue. Seems to need improvement on the UI side for the better UX. 

Nice catch for the easiness of development mode! I'm preparing the makefile script & contribution guide. 

But, if you want to move fast. You can check [playground-ui README file](https://github.com/isdzulqor/cakcuk/blob/master/playground-ui/README.md) to develop the UI. 
And please do this following steps to contribute: 
 - Fork Cakcuk Repository
 - Put your changes on the branch with `ui/` prefix. i.e: `ui/improve-ux-playground`
 - `ui/*` branch will trigger [build_ui](https://github.com/isdzulqor/cakcuk/actions?query=workflow%3A%22Build+UI%22) job. 
 - Please put preview/screenshot for your changes on your PR summary as well. 

Hope those steps clear for you! Let me know if you have any other concerns!

**Comment by isdzulqor** [comment]
Hi, this issue is closed. For now, we put intuitive information about it. Please create a new issue if you have any other concerns! 😉
